
docker build -f skill-alerts/Dockerfile -t jarbasai/ovos-skill-alerts:latest ./skill-alerts
docker build -f skill-camera/Dockerfile -t jarbasai/ovos-skill-camera:latest ./skill-camera
docker build -f skill-date-time/Dockerfile -t jarbasai/ovos-skill-date-time:latest ./skill-date-time
docker build -f skill-duckduckgo/Dockerfile -t jarbasai/ovos-skill-duckduckgo:latest ./skill-duckduckgo
docker build -f skill-easter-eggs/Dockerfile -t jarbasai/ovos-skill-easter-eggs:latest ./skill-easter-eggs
docker build -f skill-ggwave/Dockerfile -t jarbasai/ovos-skill-fallback-unknown:latest ./skill-fallback-unknown
docker build -f skill-hello-world/Dockerfile -t jarbasai/ovos-skill-hello-world:latest ./skill-hello-world
docker build -f skill-homescreen/Dockerfile -t jarbasai/ovos-skill-homescreen:latest ./skill-homescreen
docker build -f skill-jokes/Dockerfile -t jarbasai/ovos-skill-jokes:latest ./skill-jokes
docker build -f skill-parrot/Dockerfile -t jarbasai/ovos-skill-parrot:latest ./skill-parrot
docker build -f skill-personal/Dockerfile -t jarbasai/ovos-skill-personal:latest ./skill-personal
docker build -f skill-randomness/Dockerfile -t jarbasai/ovos-skill-randomness:latest ./skill-randomness
docker build -f skill-tunein/Dockerfile -t jarbasai/ovos-skill-tunein:latest ./skill-tunein
docker build -f skill-volume/Dockerfile -t jarbasai/ovos-skill-volume:latest ./skill-volume
docker build -f skill-weather/Dockerfile -t jarbasai/ovos-skill-weather:latest ./skill-weather
docker build -f skill-wikihow/Dockerfile -t jarbasai/ovos-skill-wikihow:latest ./skill-wikihow
docker build -f skill-wikipedia/Dockerfile -t jarbasai/ovos-skill-wikipedia:latest ./skill-wikipedia
docker build -f skill-wolfie/Dockerfile -t jarbasai/ovos-skill-wolfie:latest ./skill-wolfie
docker build -f skill-wordnet/Dockerfile -t jarbasai/ovos-skill-wordnet:latest ./skill-wordnet
